# Java
## 예외처리
### 사용자정의 예외 만들기
- 필요에 따라 프로그래머가 새로운 예외 클래스 정의
- 보통 Exception이나 RuntimeException 클래스 상속받아 클래스 만드는데, 필요에 따라 알맞은 예외 클래스 선택할 수 있다

```Java
class MyException extends Exception {
    MyException(String msg) { // 문자열을 매개변수로 받는 생성자
        super(msg); // 조상인 Exception 클래스 생성자 호출
    }
}
```
- 필요시 멤버변수나 메서드 추가 가능
- Exception클래스는 생성 시 String값을 받아 메시지로 저장<br>
-> 사용자정의 예외도 메시지 저장하려면, String을 매개변수로 받는 생성자 추가

**에러 메시지와 에러 코드 저장하고 얻을 수 있게 코드 개선**
```Java
class MyException extends Exception {
    // 에러 코드 값 필드
    private final int ERR_CODE;

    MyException(String msg, int errCode) { // 생성자
        super(msg);
        ERR_CODE = errCode;
    }

    MyException(String msg) { // 생성자
        this(msg, 100); // ERR_CODE를 100(기본값)으로 초기화
    }

    public int getErrCode() { // 에러 코드 얻을 수 있는 메서드
        return ERR_CODE; // 이 메서드는 주로 getMessage()와 함께 사용될 것
    }
}
```

### 예외 되던지기
- 메서드에서 발생할 수 있는 예외가 여럿인 경우, 몇 개는 try-catch문으로 직접 처리하고, 나머지는 선언부에 지정해 호출한 메서드에서 처리하도록 함으로써 양쪽에서 나눠서 처리할 수 있다
- 하나의 예외에 대해서도 양쪽에서 처리할 수 있다
<br><br>
- 예외를 처리한 후 인위적으로 다시 발생시키는 방법
- 예외 발생 가능성이 있는 메서드에서 try-catch문으로 예외처리 해주고, catch문에서 필요한 작업 후 `throw`로 다시 예외 발생시킴
- 다시 발생한 예외는 이 메서드를 호출한 메서드에게 전달되고 호출한 메서드의 try-catch문에서 예외를 또 다시 처리
- 하나의 예외에 대해 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해야 할 작업이 있을 때 사용
- 예외가 발생할 메서드에서는 try-catch문으로 예외처리를 해줌과 동시에 메서드 선언부에 발생할 예외를 `throws`로 지정해야 한다
<br><br>
- 반환값이 있는 return문은, catch블럭에서도 return문이 있어야 한다. 예외가 발생해도 값을 반환해야하기 때문이다

```Java
static int method1() {
    try {
        System.out.println("method1()이 호출되었습니다");
        return 0; // 현재 실행 중인 메서드 종료
    } catch (Exception e) {
        e.printStackTrace();
        return 1; // catch블럭 내에도 return문 필요
    } finally {
        System.out.println("method1()의 finally블럭이 실행되었습니다");
    }
}
```

- catch 블럭에서 예외 되던지기를 해서 호출한 메서드로 예외 전달하면, return문이 없어도 된다
```Java
static int method1() throws Exception { // 예외 선언
    try {
        System.out.println("method1()이 호출되었습니다");
        return 0; 
    } catch (Exception e) {
        e.printStackTrace();
        // return 1;
        throw new Exception(); // return문 대신 예외를 호출한 메서드로 전달
    } finally {
        System.out.println("method1()의 finally블럭이 실행되었습니다");
    }
}
```

**`throw new Exception();`과 `throw e;` 차이**

```Java
try {
} catch (Exception e) {
    throw new Exception(); // 예외 되던지기 방법 1
    // throw e; //예외 되던지기 방법 2
}
```
- `throw new Exception();`<br>
: 새로운 Exception 객체를 생성하여 던진다<br>
: 원래 예외 정보 사라진다 <br>
: 이전 예외의 스택 트레이스 포함하지 않는다<br>
: 새로운 컨텍스트나 메시지 부여해 별도의 예외를 던질 때 사용<br>
- `throw e;`<br>
: 원래 발생한 예외 객체를 그대로 다시 던진다<br>
: 예외 스택 트레이스 정보 유지 -> 예외 발생 지점 정확히 추적 가능<br>
: 원래 예외 정보 유지해야하는 경우 사용


- finally블럭 내에도 return문 사용할 수 있으며, 이는 try블럭이나 catch블럭의 return문 다음에 수행된다. 최종적으로 finally블럭 내의 return문 값이 반환된다

### 연결된 예외
- 한 예외가 다른 예외를 발생시킬 수도 있다
- 예외 A가 예외 B 발생시키면, A는 B의 '원인 예외'

**다른 예외 발생시키기**
```Java
try {
    startInstall();
} catch (SpaceException e) {
    InstallException ie = new InstallException("설치 중 예외발생"); // 예외 생성
    ie.initCause(e); // InstallException의 원인 예외를 SpaceException으로 지정
    throw ie; // InstallException 발생
} catch (MemoryException me) { }
```
- InstallException을 생성한 후 `initCause()`로 SpaceException을 InstallException의 원인 예외로 등록한 후 `throw`로 이 예외 던짐
<br><br>
- `initCause()`는 Exception클래스의 조상인 Throwable클래스에 정의되어 있어 모든 예외에서 사용 가능
- `Throwable initCause(Throwable cause)`: 지정한 예외를 원인 예외로 등록
- `Throwable getCause()`: 원인 예외 반환

**발생한 예외를 그냥 처리하지 않고, 원인 예외로 등록해서 다시 예외를 발생시키는 이유**
1. 여러가지 예외를 하나의 큰 분류의 예외로 묶어서 다루기 위해<br>
-> 만약 조상 예외로 catch블럭을 작성하면, 실제 발생한 예외를 파악할 수 없다는 문제가 생기고, 상속관계 변경도 부담 된다<br>
-> 그래서 예외가 원인 예외를 포함할 수 있게 한 것이다
2. checked예외를 unchecked예외로 바꿀 수 있도록 하기 위해<br>
-> 만약 checked예외가 발생해도 예외를 처리할 수 없는 상황이 발생하면, 의미없는 try-catch으로 억지로 예외처리를 하지 않아도 된다<br>
-> RuntimeException 생성자를 이용해 등록할 수 있다

원인 예외 등록 전
```Java
static void startInstall() throws SpaceException, MemoryException {
    if (!enoughSpace()) {
        throw new SpaceException("설치할 공간이 부족합니다.");
    }
    if (!enoughMemory()) {
        throw new MemoryException("메모리가 부족합니다."); // 이 부분 수정해보자
    }
}
```
원인 예외 등록 후
```Java
static void startInstall() throws SpaceException, MemoryException {
    if (!enoughSpace()) { 
        throw new SpaceException("설치할 공간이 부족합니다.");
    }
    if (!enoughMemory()) {
        throw new RuntimeException(new MemoryException("메모리가 부족합니다.")); // unchecked 예외로 변경
    }
}
```
- `RuntimeException(Throwable cause)`: 원인 예외를 등록하는 생성자

예제 코드
```Java
public class ChainedExceptionEx {
    public static void main(String[] args) {
        try {
            install();
        } catch (InstallException e) {
            e.printStackTrace();
        }
    }

    static void install() throws InstallException {
        try {
            startInstall();
        } catch (SpaceException se) {
            InstallException ie = new InstallException("설치 중 예외 발생");
            ie.initCause(se); // 원인예외 등록
            throw ie; // InstallException 발생시키기 
        } catch (MemoryException me) {}
    }

    static void startInstall() throws SpaceException, MemoryException {
        if (!enoughSpace()) { // 충분한 설치 공간 없으면...
            throw new SpaceException("설치할 공간이 부족합니다."); // SpaceException 발생
        }
        if (!enoughMemory()) { 
            throw new MemoryException("메모리가 부족합니다.");
        }
    }
    static boolean enoughSpace() {
        return false;
    }

    static boolean enoughMemory() {
        return true;
    }
}

class InstallException extends Exception {
    InstallException(String msg) {
        super(msg);
    }
}

class SpaceException1 extends Exception {
    SpaceException1(String msg) {
        super(msg);
    }
}

class MemoryException1 extends Exception {
    MemoryException1(String msg) {
        super(msg);
    }
}
```

결과
```
Example.InstallException: 설치 중 예외 발생
	at Example.ExceptionEx23.install(ExceptionEx23.java:19)
	at Example.ExceptionEx23.main(ExceptionEx23.java:6)
Caused by: Example.SpaceException1: 설치할 공간이 부족합니다.
	at Example.ExceptionEx23.startInstall(ExceptionEx23.java:33)
	at Example.ExceptionEx23.install(ExceptionEx23.java:16)
	... 1 more

Process finished with exit code 0
```
- 예외가 체인 형태로 연결되어 있을 때, Caused by는 현재 예외를 유발한 원인 예외를 표시